include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'pubspec.yaml'
  errors:
    invalid_annotation_target: ignore # https://github.com/rrousselGit/freezed/issues/527#issuecomment-934281148
