name: flutter_hackathon_2024
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  email_validator: ^3.0.0
  flame: ^1.21.0
  flame_riverpod: ^5.4.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0

  flutter_hooks: ^0.20.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  go_router: ^14.3.0
  hooks_riverpod: ^2.6.1
  mockito: ^5.4.4
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.0
  supabase_flutter: ^2.8.0
  swipable_stack: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  go_router_builder: ^2.7.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - dotenv
